apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app-psql
  labels:
    app: trading-app-psql
    tier: psql
spec:
  selector:
    matchLabels:
      app: trading-app-psql
      tier: psql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trading-app-psql
        tier: psql
    spec:
      containers:
        - image: jason121301/trading-psql:latest
          name: psql
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trading-app
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: trading-app
                  key: user
            - name: POSTGRES_DB
              value: jrvstrading
          ports:
            - containerPort: 5432
              name: psql
          volumeMounts:
            - name: psql-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: psql-persistent-storage
          persistentVolumeClaim:
            claimName: psql-pv-claim
